# Generated by Django 4.2.2 on 2023-07-02 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='event_managment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=250)),
                ('is_free', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='speaker_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('biography', models.TextField()),
                ('optional_photo', models.ImageField(blank=True, null=True, upload_to='speaker_photo')),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=25)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='schedule_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('topic', models.CharField(max_length=255)),
                ('event_managment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event_app.event_managment')),
                ('speaker_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event_app.speaker_management')),
            ],
        ),
        migrations.CreateModel(
            name='participant_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=25)),
                ('events_attending', models.ManyToManyField(blank=True, to='Event_app.event_managment')),
            ],
        ),
        migrations.CreateModel(
            name='event_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=3, max_digits=10)),
                ('payment_method', models.CharField(max_length=255)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(max_length=255)),
                ('payment_status', models.CharField(choices=[('Paid', 'paid'), ('Pending', 'pending'), ('Failed', 'failed')], default='Pending', max_length=20)),
                ('event_managment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event_app.event_managment')),
                ('participant_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event_app.participant_management')),
            ],
        ),
    ]
