# Generated by Django 4.2.2 on 2023-07-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_payment',
            name='payment_method',
            field=models.CharField(choices=[('MoMo', 'Mobile Money'), ('PayPal', 'PayPal'), ('Airtel Money', 'Airtel Money'), ('MasterCard', 'MasterCard'), ('Visa', 'Visa Card'), ('Wire transfer', 'Wire transfer'), ('Western Union', 'Western Union')], default='MoMo', max_length=255),
        ),
    ]
