# Generated by Django 4.2.2 on 2023-07-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_app', '0002_alter_event_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant_management',
            name='password',
            field=models.CharField(default='0000', max_length=50),
        ),
    ]
