# Generated by Django 3.2.20 on 2023-07-20 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event_app', '0004_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_managment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='Event_app.category'),
        ),
        migrations.AlterField(
            model_name='event_payment',
            name='participant_management',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Event_app.participant_management'),
        ),
        migrations.AlterField(
            model_name='participant_management',
            name='events_attending',
            field=models.ManyToManyField(blank=True, related_name='participants', to='Event_app.event_managment'),
        ),
        migrations.AlterField(
            model_name='schedule_management',
            name='speaker_management',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='Event_app.speaker_management'),
        ),
    ]
